### ISSUE TITLE
Sound effects Only work when in the same match with Sonic

### ISSUE THREAD

**Issue by tylerf115** [Project-M-CC/knuckles#5]
Knuckles Voice and sound effects only work when in the same match. And the Knuckles .rel file does not work either

**Comment by Yohan1044** [comment]
I can't actually attest to the config files provided in the build/ in the repo... but it sounds like your Knuckles PSA and his Brawl Ex configs/.rel are out of sync.

Knuckles PSA now points to Sonic's soundbank. If your Knuckles config files are still loading Porky's soundbank, then you'll only get voice when Sonic's soundbank is loaded... which is likely only when you're fighting Sonic. As for the .rel, I suspect it's coming from the same root problem. Out of sync files.

**Comment by tylerf115** [comment]
Do you have to use the BrawlEX build? I use the 3.61 cc edition and i have no idea where to put the config files.

**Comment by Yohan1044** [comment]
Technically no, you don't need to use BrawlEx. You can use 3.61 CC or similar (going back to using its .rel but the new fighter folder contents). But to get the Knuckles new PSA to be voiced, you'd need to copy over the 45.sawnd to the sfx folder and edit his codes within the GCT to point to Sonic's soundbank.

Open you GCT file and search for the hex string  04AD8A940000013B  and replace it with 04AD8A9400000026

No more help on this issue though. It should be closed.

**Comment by tylerf115** [comment]
bruh thank you so much, all these codes and files confuse the shit out me!
